name: Turborepo CICD
on:
  push:
    branches: [main]

jobs:
  get-diff:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.set.outputs.web }}
      ws-backend: ${{ steps.set.outputs.ws-backend }}
      http-backend: ${{ steps.set.outputs.http-backend }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup local npm
        uses: actions/setup-node@v6
        with:
          node-version: 22
        #   cache: "pnpm"

      - name: "Enable corepack"
        run: corepack enable

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Detect change"
        id: set
        run: |
          pnpm exec turbo run build --affected --dry=json > diff.json 
          echo "http-backend=$(grep -q "http-backend" diff.json && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "web=$(grep -q "web" diff.json && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "ws-backend=$(grep -q "ws-backend" diff.json && echo true || echo false)" >> $GITHUB_OUTPUT
          cat diff.json
          grep -q "web" diff.json && echo "FOUND" || echo "NOT FOUND"
          grep -q "http-backend" diff.json && echo "FOUND" || echo "NOT FOUND"
          grep -q "ws-backend" diff.json && echo "FOUND" || echo "NOT FOUND"
  build:
    name: Build and push image
    needs: get-diff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: "Login to Docker"
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "Build and push express app"
        if: needs.get-diff.outputs.http-backend == 'true'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./apps/http-backend/.Dockerfile
          push: true
          tags: divv919/excalidraw-http-backend:${{github.sha}}

      - name: "Build and push websockets app"
        if: needs.get-diff.outputs.ws-backend == 'true'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./apps/ws-backend/.Dockerfile
          push: true
          tags: divv919/excalidraw-ws-backend:${{github.sha}}

      - name: "Build and push nextjs app"
        if: needs.get-diff.outputs.web == 'true'
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./apps/web/.Dockerfile
          push: true
          tags: divv919/excalidraw-web:${{github.sha}}

  pull-changes:
    runs-on: ubuntu-latest
    needs: [get-diff, build]
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ "${{ needs.get-diff.outputs.http-backend }}" == "true" ]; then
              docker pull divv919/excalidraw-http-backend:${{ github.sha }}
              docker stop excalidraw-http-backend || true
              docker rm excalidraw-http-backend || true
              docker run -d -p 3001:3001 -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
              -e PORT=3001 \
              --name=excalidraw-http-backend \
              divv919/excalidraw-http-backend:${{ github.sha }}
            fi

            if [ "${{ needs.get-diff.outputs.ws-backend }}"  == "true" ]; then
              docker pull divv919/excalidraw-ws-backend:${{ github.sha }}
              docker stop excalidraw-ws-backend || true
              docker rm excalidraw-ws-backend || true
              docker run -d -p 8080:8080 \
              -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
              -e PORT=8080 \
              --name=excalidraw-ws-backend \
              divv919/excalidraw-ws-backend:${{ github.sha }}
            fi

            if [ "${{ needs.get-diff.outputs.web }}" == "true" ]; then
             docker pull divv919/excalidraw-web:${{ github.sha }}
             docker stop excalidraw-web || true
             docker rm excalidraw-web || true
             docker run -d -p 3000:3000 \
             -e NEXT_PUBLIC_HTTP_URL=${{ secrets.NEXT_PUBLIC_HTTP_URL }} \
             -e NEXT_PUBLIC_WS_URL=${{ secrets.NEXT_PUBLIC_WS_URL }} \
             -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
             -e GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} \
             -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
             -e GITHUB_SECRET=${{ secrets.GITHUB_SECRET }} \
             -e GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }} \
             -e PORT=3000 \
             -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
             --name=excalidraw-web \
             divv919/excalidraw-web:${{ github.sha }}
            fi
